### ISSUE TITLE
Create pattern Organism::Intro--Interior~Text

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/Pattern-Library#138]

**Comment by kristianserrano** [comment]
@laurenhamel It looks like we mislabeled this pattern in Pattern Lab, but for @nikdragovic, this is up at http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-intro-text

**Comment by laurenhamel** [comment]
We ended up leaving off the interior labels for all of the interior intro types, but given that the names will still be unique and recognizable enough, I think that it’s okay.
