### ISSUE TITLE
Create pattern Organism::Section--Main

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/Pattern-Library#140]

**Comment by laurenhamel** [comment]
@kristianserrano, just dropping a note here. I noticed that when the main section get's stacked on small screens, there isn't a grid gap between the main body and sidebar. We'll want to fix this before closing this issue for the pattern, but it's not a deal breaker in terms of just getting the staging environment setup for now.

**Comment by kristianserrano** [comment]
@laurenhamel Looks like I had set `grid-column-gap` instead of `grid-gap`. Fixing it now.

**Comment by lovinscari** [comment]
@kristianserrano Is there still testing to complete on this issue?

**Comment by kristianserrano** [comment]
@lovinscari This issue was resolved with #234. Moving it to To Accept.
