### ISSUE TITLE
Implement pattern templates and partials structure

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/Pattern-Library#144]
Pattern templates and partials (atoms, molecules, compounds, etc.) will all need to be dumped out of the pattern library and imported into the templating engine.

## To Do

- [x] Ensure that pattern names/IDs are correct when dumping/exporting patterns from the pattern library
- [x] Reconfigure the `grunt push` task to dump the patterns and data files from pattern library in the right place(s) in the templating engine
- [x] Dump/export the patterns from the pattern library to the templating engine

**Comment by laurenhamel** [comment]
I think this is a hold over from "To Accept for Launch." The work has already been done in order to get this `push` process setup for dumping patterns from the pattern library into the templating engine, and we do a mandatory push/dump each time we deploy as part of the process. I think this issue can be closed, but I would like to make sure @nikdragovic and @kristianserrano are in agreement.

**Comment by nikdragovic** [comment]
I am fine with closing it, thanks @laurenhamel
