### ISSUE TITLE
Create pattern for Organism::Section--Related

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#150]

**Comment by laurenhamel** [comment]
This is pattern is no longer needed given `compounds-releated-cards`, `compounds-releated-links`, and `compounds-releated-topics`.

**Comment by kristianserrano** [comment]
If this pattern is no longer needed, should it be in To Deploy or just closed?

**Comment by laurenhamel** [comment]
I think approval on the other patterns that were mentioned should be sufficient enough to close this specific issue.

**Comment by nikdragovic** [comment]
@kristianserrano @laurenhamel Flagged as invalid and closing.
