### ISSUE TITLE
Create pattern for Template::Service--Directory

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#153]

**Comment by nikdragovic** [comment]
Includes filter as well as getting Services on the page.
Base of this issue is complete, just need to finalize templating strategy.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm dropping this in blocked for the time being since it would be beneficial to have the data definition for this page first before finishing up the pattern.

**Comment by kristianserrano** [comment]
Just to make a note here as well, the content type and page has been created. The page XML has also been published to dev.libraries.emory.edu.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready to test. See the PR that I opened for it, #236.

**Comment by kristianserrano** [comment]
@nikdragovic This is ready for acceptance.

http://qa.libraries.emory.edu/services/

**Comment by laurenhamel** [comment]
@kristianserrano, this PR is still outstanding in the `Pattern-Library` repo. See #236. I'm moving this back to "To Test" for now until you're able to merge it.
