### ISSUE TITLE
Create pattern for Template::Research-Help--Directory

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#154]

**Comment by lovinscari** [comment]
@kristianserrano update status and direction by COB 5/24.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm changing the assignee to me to more evenly distribute points.

**Comment by laurenhamel** [comment]
@nikdragovic and @kristianserrano, just to clarify, we did come to the decision that the filters should be left off this page, correct? I assume we'll want to leave off the "View All" button as well since we're not currently porting over enough content into Research Help pages to warrant it.

**Comment by nikdragovic** [comment]
@laurenhamel @kristianserrano Should I be reviewing issues that moved into "Accept for Launch" today, or not yet? I think this issue corresponds to this page:

https://cascade.emory.edu/entity/open.act?id=753b3e520ae72098489eb62406df4288&type=page

**Comment by nikdragovic** [comment]
@laurenhamel @kristianserrano Just wanted to comment on this thread to make it easier to locate and review the question above.

**Comment by nikdragovic** [comment]
Reference links:

https://cascade.emory.edu/entity/open.act?id=753b3e520ae72098489eb62406df4288&type=page

http://qa.libraries.emory.edu/research-help-directory
