### ISSUE TITLE
Create pattern for Compound::Pill-Menu

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#155]

**Comment by laurenhamel** [comment]
This pattern was moved into the `molecules-filter-button`.

**Comment by kristianserrano** [comment]
Is that a separate issue, and should this issue be closed or is it still pending review/merging/deployment/etc.?

**Comment by laurenhamel** [comment]
This can be closed. My last comment was meaning to say that I moved this pill menu from the compound level and felt that it more appropriately fit along with the other filter patterns.
