### ISSUE TITLE
Create new pattern Molecule::Branding--Footer

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#158]
## Testing

`pattern-library` [molecules-branding-footer](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=molecules-branding-footer)

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance. Just an FYI that when you do get around to testing this, you'll notice that the top of the logo gets cutoff. This is intended and due to the negative margin that we have in place in order to yield the desired overhang within the footer.

**Comment by nikdragovic** [comment]
@laurenhamel Accepted.
