### ISSUE TITLE
Create new pattern Molecule::Social-Media

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#159]
## Testing

`pattern-library` [molecules-social-media](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=molecules-social-media)

**Comment by laurenhamel** [comment]
Reassigning to myself to redistribute points.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance testing. The preview is mostly for design purposes as we haven't yet populated any current social media links.

**Comment by nikdragovic** [comment]
@laurenhamel Accepted.
