### ISSUE TITLE
Create new pattern Compound::Nav-Menu--Main

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#162]
## Testing

`pattern-library` [compounds-nav-menu-main](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=compounds-nav-menu-main)

**Comment by laurenhamel** [comment]
Reassigning this issue to myself to redistribute points.

**Comment by laurenhamel** [comment]
@kristianserrano, this is done and ready for testing for the most part. It will still need integration of the search menu stuff you've been working on, but the core of the main navigation sans search should be compiled and ready to go in this pattern.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance and has been deployed to the pattern library. Check the description above for testing links.

**Comment by nikdragovic** [comment]
@laurenhamel Thanks, this looks good. I know we didn't have specs for
interaction from the design, but do you think only one dropdown should
appear at a time? I can get all of them dropped down by clicking.

**Comment by laurenhamel** [comment]
@nikdragovic, yes, that was built into the pattern, but it looks like the deploy script wasn't fully compiling the JS file, which was resulting in an error. I fixed the deploy script, rebuilt, and redeployed, so everything should be working again.

**Comment by nikdragovic** [comment]
@laurenhamel I thought we were going to do click for dropdown, not hover,
but hover works for me as long as mobile issues can be sorted out. Sorry -
should have been documented more clearly in the issue.

I see a blue box/border around the nav items when I click. Will this be in
production?

**Comment by laurenhamel** [comment]
@nikdragovic, yes, click is the native control, but hover was to desktop version of the dropdown menus. If you shrink your screen width (you can click `S` in the pattern lab's navigation bar also), you'll notice that the mobile navigation menu is still click dependent. Also, to answer your second question, yes the blue box will be in production as it's a standard focus feature for accessibility purposes. You'll likely notice the same effect around other buttons as well throughout the site.

**Comment by nikdragovic** [comment]
@laurenhamel Okay, thanks! Was just wondering about the border widths
around the buttons; not a big deal though.

**Comment by nikdragovic** [comment]
@laurenhamel Do we need work on this issue in order to add "View All" to the bottom of Materials and Tools, or will that be incorporated elsewhere (like the dropdown elements themselves)?

**Comment by laurenhamel** [comment]
@nikdragovic, I'm not sure what you're referring to in the latter part of your comment, but if there needs to be *View All* buttons added to those menus, I think @kristianserrano and I can agree that it will need to be a new issue. That may require some additional restyling of the various menu styles themselves, which extends beyond just this pattern.

**Comment by nikdragovic** [comment]
Thanks @laurenhamel. You answered the latter part yourself. I am trying to comment on the correct issues but sometimes am not sure if my questions relate to Cascade, Pattern Lab, etc. and sometimes what component/organism/etc. might be in question.

**Comment by nikdragovic** [comment]
Accepted.
