### ISSUE TITLE
Incorporate prefiltering for categories into Services Directory page 

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#168]

**Comment by laurenhamel** [comment]
This is more of an enhancement to the Service Directory page to add in a filtered view. Based on our previous conversations, we'll likely want to incorporate the use of query parameters to handle this.

**Comment by laurenhamel** [comment]
@kristianserrano, I updated the name of this issue to be more clear and better describe the work we're trying to capture. This is also tied into #153, which I'm assigned to and currently have in progress, so it may be that I end up working on this while finishing up that other pattern.

**Comment by kristianserrano** [comment]
That makes sense. Thank you, @laurenhamel !

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing, but it will need to be tested in the `templating-engine` repo. See the PR I opened for this, emory-libraries/templating-engine#58. Also, it's worth noting that this PR this shouldn't get merged until after emory-libraries/templating-engine#57 is merged.
