### ISSUE TITLE
Create new pattern Template::Event--Event

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#173]
## Testing

`qa` [/events?feed=https://www.trumba.com/calendars/robert-woodruff-library.json&id=133548190](http://qa.libraries.emory.edu/events?feed=https://www.trumba.com/calendars/robert-woodruff-library.json&id=133548190)

**Comment by kristianserrano** [comment]
Waiting for fix to get pushed to dev so that it can be pulled into this branch.

**Comment by kristianserrano** [comment]
We're running into an issue with being able to assign the `<title>` element in `<head>` after fetching the event data. For demo purposes, we're leaving it as is and will attempt to resolve it later.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for testing. See above for the testing link. This page is a dynamic endpoint that we've registered within the templating engine, which uses query string parameters to fetch the event by feed and ID.
