### ISSUE TITLE
Create new pattern Template::Exhibition--Gallery

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#174]

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing.

**Comment by nikdragovic** [comment]
Reference links: 

https://cascade.emory.edu/entity/open.act?id=9a3817740ae720982dc27e3375122ec1&type=page

http://qa.libraries.emory.edu/events-and-exhibits/exhibits/index
