### ISSUE TITLE
Create new pattern Template::News--Periodical

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#176]
## Testing

`qa` [/news/rose-library-magazine](http://qa.libraries.emory.edu/news/rose-library-magazine)

**Comment by laurenhamel** [comment]
@nikdragovic, this has been deployed to `qa` and is ready for acceptance. See above for testing links.

**Comment by nikdragovic** [comment]
@laurenhamel Accepted.
