### ISSUE TITLE
Create new pattern Template::Archive-Directory

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#178]

**Comment by laurenhamel** [comment]
@kristianserrano, I see you marked this as invalid. Are you thinking that this will be an irrelevant page type for the time being given that news and blogs will live on WordPress? For this news archive directory especially, it mostly acts as a navigation tool to allow users to quickly jump to news articles and/or blog posts from a given time period. Would this still be something we want to implement even if it's linking out to the WordPress site?

![Screen Shot 2019-05-14 at 8.31.36 AM.png](https://images.zenhubusercontent.com/5be0a9477c17fe10e1b41701/a2a5b776-066e-4ea0-afc3-7032d752560a)

**Comment by kristianserrano** [comment]
I saw this mockup as being a presentation based on how we currently manage and present the news archives using Cascade. It's a product of trying to organize the articles in the CMS itself. WordPress solves that problem for us and renders this solution obsolete.

**Comment by laurenhamel** [comment]
That makes sense, so I assume any links to a news archive page will then link out to WordPress along with news articles, blog posts, searching/filtering, etc. I can make note of this in the Figma file along with #177.

**Comment by laurenhamel** [comment]
In thinking about this again, I had listed this under a generic page type within Figma (i.e., not being specific to news) under the impression that we maybe would want to adapt this design to be usable for things like events, exhibits, and/or periodical. The same goes for the archive results template (#178). What are your thoughts there?

**Comment by kristianserrano** [comment]
Lauren and I discussed this just now. To summarize, unless there's an actual need for something this, I suggest we keep this in a backlog for now. We're not even sure that this design is something that would test well with users. Essentially, it'd be a solution in search of a problem at this stage.

**Comment by laurenhamel** [comment]
Closing because this was marked as invalid. A new issue can be opened in the future if circumstances related to this changes.
