### ISSUE TITLE
Create new pattern Template::Index

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#179]
## Testing

`qa` [/tools1](http://qa.libraries.emory.edu/tools1)

**Comment by laurenhamel** [comment]
Reassigning this issue to myself to redistribute points.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing, and I went ahead and deployed it to `dev`.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance and has been deployed to `qa`. I'm not sure if you created a sample page in Cascade yet, so I left off testing links in the description above. Please update this issue with the link if you draft a test page and publish it out.

**Comment by nikdragovic** [comment]
@laurenhamel Here's the test page we looked at on our call:

http://qa.libraries.emory.edu/tools1
 
Looks pretty good to me; certainly ready for stakeholder review Monday.
