### ISSUE TITLE
Create new pattern Template::Form

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#181]
## Testing

`qa` [/services/visitor-library-materials-request](http://qa.libraries.emory.edu/services/visitor-library-materials-request)

**Comment by laurenhamel** [comment]
@kristianserrano, since this is a template pattern, I think this needs to be moved back to "In Progress," and additional work should be done to also include setup within the templating engine.

**Comment by laurenhamel** [comment]
@kristianserrano, I wanted to double check to see if you got my comment above. Since we just merged some changes into the templating engine, I think now would be a good time to work on building the mutations for this template in the templating engine. I imagine that it won't be too time consuming given the page type. If you can get this done by EOD, I'm going to try reviewing and closing out the remaining PRs you submitted.

**Comment by laurenhamel** [comment]
Moving this back to "In Progress" to help declutter everything that needs to be tested.

**Comment by kristianserrano** [comment]
@laurenhamel I'm going to finish this up.

**Comment by kristianserrano** [comment]
@laurenhamel This has been updated with dev and pushed on all three repos.

**Comment by laurenhamel** [comment]
@nikdragovic, this has been deployed to `qa`. I'm not sure if there are any page types using this pattern currently, so I left the testing links above TBD for the time being.

**Comment by nikdragovic** [comment]
@laurenhamel I am accepting based on what I see here:

http://qa.libraries.emory.edu/services/visitor-library-materials-request

One note - I think we may want to see if we can get the styles of the form to match the site, but that would be on the SpringShare / LibWizard side.

**Comment by kristianserrano** [comment]
@nikdragovic agreed. We'll want to update the in LibWizard like we had once before (which now seem to be missing), but it should be noted that those styles will appear on all of the other sites that use LibWizard forms.

**Comment by nikdragovic** [comment]
@laurenhamel Sorry, it looks like I actually wasn't able to publish the dummy intro text here, so let's look at that: https://cascade.emory.edu/entity/open.act?id=01b223510ae720984942c44cdabb5a46&type=page&confId=28b32c840ae720982da9b0c813ad929a

**Comment by nikdragovic** [comment]
@kristianserrano Sorry, what is missing? The styles in LibWizard, or some sort of link?

**Comment by kristianserrano** [comment]
@nikdragovic The styles that used to be in LibWizard that were based on our current site.

**Comment by laurenhamel** [comment]
@nikdragovic, has this been resolved? I was going to deploy everything from Sprint 12 to `staging`, but I see that this is still not formerly accepted. As @kristianserrano was mentioning, the CSS styles differ in the LibWizard forms due to embeds. To help get this issue accepted, I think it's probably best that we create a new issue to capture the work needed around having those styles updated.

**Comment by nikdragovic** [comment]
@laurenhamel Yes, let's create a new issue for the LibWizard work. The reason this is not yet accepted is that I am still not seeing the intro text in Cascade display:

http://qa.libraries.emory.edu/services/visitor-library-materials-request

**Comment by kristianserrano** [comment]
@nikdragovic and @laurenhamel I began work on this last night. Should be wrapped up at some point today. @laurenhamel looking at the related main and intro hbs files, I'm not quite sure why it's not populating already. Might need to walk through it with you to track it down.

**Comment by kristianserrano** [comment]
@laurenhamel and @nikdragovic I've modified the styles for form pages to display the introduction. This is ready to test (again).

**Comment by nikdragovic** [comment]
@kristianserrano I still can't get this intro text to display:

https://cascade.emory.edu/entity/open.act?id=01b223510ae720984942c44cdabb5a46&type=page&confId=28b32c840ae720982da9b0c813ad929a

**Comment by kristianserrano** [comment]
It's not deployed to QA yet. I was formally waiting for PR review. Just wanted to let you know it was worked on and solved. @laurenhamel I can merge and deploy to QA if that's ok with you.

**Comment by nikdragovic** [comment]
@kristianserrano Apologies, didn't realize it was in this column.

**Comment by nikdragovic** [comment]
I am still unable to get the intro text to display here:

http://qa.libraries.emory.edu/services/visitor-library-materials-request

**Comment by nikdragovic** [comment]
The label is displaying correctly on the Services Directory after reindexing, though:

http://qa.libraries.emory.edu/services/index

**Comment by laurenhamel** [comment]
@nikdragovic, is your page cached? I just tried the link again, and I'm seeing the subtitle text.

**Comment by nikdragovic** [comment]
Thanks @laurenhamel. It worked; I forgot to try that. Accepting now.
