### ISSUE TITLE
Create new pattern Template::Landing

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#184]

**Comment by kristianserrano** [comment]
The mutations took longer than expected for my first run at the process.

**Comment by nikdragovic** [comment]
Reference links (I just created this page, so nothing is showing up yet):

https://cascade.emory.edu/entity/open.act?id=d96ab3c80ae720981fc30b27aceaae67&type=page&confId=07f70ffd0ae720987eb6affbab462a74

http://qa.libraries.emory.edu/research/index

**Comment by nikdragovic** [comment]
Additional link: https://staging.libraries.emory.edu/tools/index
