### ISSUE TITLE
Create new pattern Template::Home

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#185]
## Testing

`pattern-library` [templates-home](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home)
`qa` [/](https://qa.libraries.emory.edu/)

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. One thing worth noting, we haven't yet built out the mutations for hours and the search menu, so I put in some placeholder/static content for the time being.

**Comment by laurenhamel** [comment]
I'm moving this into blocked because of the suspected firewall issue with our use of `curl` to fetch feed data, which is timing out in server environments. Currently, middleware is investigating the issue and will report back.

**Comment by laurenhamel** [comment]
The `curl` request issue has been resolved. The server environment requires a proxy, which middleware has shared with the development team.

**Comment by laurenhamel** [comment]
This is ready for testing. See above for testing links.
