### ISSUE TITLE
Create new pattern Organism::Flow--Feed-Preview

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#186]
## Testing

`pattern-library` [organisms-flow-feed-preview](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-flow-feed-preview)

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance. Do note, this is static content for the time being, but once we start incorporating this into template-level patterns, we will be pulling in live feed data from Trumba, etc.

**Comment by nikdragovic** [comment]
@laurenhamel Accepted; looks great.
