### ISSUE TITLE
Create new pattern Organism::Intro--Interior~Alt-Heading

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#191]

**Comment by laurenhamel** [comment]
@kristianserrano, I'm finishing this up since I had some outstanding work on my end that I didn't commit yet.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. See the `feature/intro-alt-heading` branch in the `template-sass` and `Pattern-Library` repos.

**Comment by kristianserrano** [comment]
Looks good, @laurenhamel . If you make it a PR, I'll merge and deploy to the pattern library site.

**Comment by kristianserrano** [comment]
@nikdragovic This has been deployed to the Pattern Library and can be seen at 
http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-intro-alt-heading
