### ISSUE TITLE
Create pattern for Organism::Intro--Interior~Full-Hero

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#198]

**Comment by laurenhamel** [comment]
@kristianserrano, in regards to my comments to the PRs for #198, you could possibly move this into "In Progress" and work on it simultaneously with that issue. You may even want to work this into those existing PRs. Refer to the comments in the PR, emory-libraries/template-sass#7.

**Comment by kristianserrano** [comment]
Since `fitted-hero` is becoming full-width and given the possibility of extending that pattern to include a `-fitted` class, I'm closing this as a duplicate of #197.
