### ISSUE TITLE
Create new pattern Organism::Intro--Home

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#199]
## Testing

`pattern-library` [organisms-intro-home](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-intro-home)

**Comment by nikdragovic** [comment]
Blocked because of a misplaced dependency.

**Comment by kristianserrano** [comment]
@laurenhamel this is ready to test.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance. See above for the testing link.

**Comment by nikdragovic** [comment]
@laurenhamel Looks great but I would like to discuss in person.

**Comment by nikdragovic** [comment]
@laurenhamel @kristianserrano We have two searches on the homepage. We may want to reconsider this but it's in the design so it's fine for launch.
