### ISSUE TITLE
Create new pattern Organism::Footer

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#200]
## Testing

`pattern-library` [organisms-footer](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-footer)

**Comment by laurenhamel** [comment]
Reassigning this to myself and picking it up since it's next in priority order.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. I anticipate some additional modifications to the organization of the JSON data model and the addition to some inline mutations will be needed  once we start integrating it into template patterns. For now, though, this seems to be working nicely.

**Comment by laurenhamel** [comment]
This is ready for acceptance. See above for testing links. Do note, this is only visual and functional testing and acceptance at this time as this pattern has not yet been integrated into our template pages.
