### ISSUE TITLE
Create new pattern Organism::Header

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#201]
## Testing

`pattern-library` [organisms-header](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-header)

**Comment by nikdragovic** [comment]
@kristianserrano What is the status of the Select a Library menu in Cascade - it will go in Global, correct?

**Comment by laurenhamel** [comment]
I'm going to start work on this tomorrow morning to help get this cranked out, so reassigning to myself, which should also help redistribute points.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. I anticipate some additional modifications to the organization of the JSON data model and the addition to some inline mutations will be needed  once we start integrating it into template patterns. For now, though, this seems to be working nicely.

**Comment by laurenhamel** [comment]
This is ready for acceptance. See above for testing links. Do note, this is only visual and functional testing and acceptance at this time as this pattern has not yet been integrated into our template pages.

**Comment by laurenhamel** [comment]
This is ready for acceptance. See above for testing links. Do note, this is only visual and functional testing and acceptance at this time as this pattern has not yet been integrated into our template pages.
