### ISSUE TITLE
Create new pattern Organism::Nav-Bar--Main

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#203]
## Testing

`pattern-library` [organisms-nav-bar-main](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-nav-bar-main)

**Comment by laurenhamel** [comment]
Reassigning this issue to myself to redistribute points.

**Comment by laurenhamel** [comment]
@kristianserrano, since we reviewed this and #162 yesterday afternoon, I'm wondering if we should just go ahead and merge these two PRs back into our `dev` branch. If you're not opposed to the idea, I may just self-close the PRs unless you have time to do so.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance and has been deployed to `qa`. Check the description above for testing links.

**Comment by nikdragovic** [comment]
@laurenhamel Is there a way to apply styling to the Select a Library dropdown? I showed slide 3 here to directors a few months ago:

https://docs.google.com/presentation/d/19p3qEgDYViAKjG07wlu7lkXvEQETrdPJnhdpTh5tgKU/edit?usp=sharing

**Comment by laurenhamel** [comment]
@nikdragovic, presently we're not using dropdown menus that pattern in favor of a select list made into a Vue component, which is mostly using browser-native select styles. Since we opted against the dropdown menus in the utility navigation, I don't think we've built out that style of dropdown menu, so using the select boxes was more reasonable for the time being. I think converting this into dropdown menus (similar to the navigation menus and/or along with utility dropdown menus) could be an enhancement post launch.

**Comment by nikdragovic** [comment]
@laurenhamel Understandable. I'll just make sure we flag this for
documentation to make sure I can answer to stakeholders if asked.

**Comment by nikdragovic** [comment]
@laurenhamel @kristianserrano Can you tell me where to edit the "Select a Library" dropdown options? I need to reorder and add to reflect what we put in the site map:

Business
Center for Digital Scholarship
Cox Hall Computing Center
Health Sciences
Law
Library Service Center
Music and Media
Oxford College
Rose
Science Commons
Theology
Woodruff

It looks like this is managed in Global Content?

**Comment by laurenhamel** [comment]
@kristianserrano should be able to give you a better idea of where the *Select a Library* items are within Cascade, but as far as the pattern library preview, it's static content that we'd need to change on our end. This pattern will get integrated once we get header stuff done.

**Comment by nikdragovic** [comment]
@laurenhamel Thanks for the clarification!

**Comment by nikdragovic** [comment]
Accepted.
