### ISSUE TITLE
Create new pattern Compound::Tab-Menu

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#205]
## Testing

`pattern-library` [compounds-tab-menu](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=compounds-tab-menu)

**Comment by laurenhamel** [comment]
@nikdragovic, this has been deployed to the pattern library and is ready for acceptance. See above for testing links.

**Comment by nikdragovic** [comment]
@laurenhamel This looks fine but I'm not sure there's anything for me to test at this level. One question - are the text options hard-coded, or editable somewhere in the CMS?

**Comment by laurenhamel** [comment]
@nikdragovic, the tabs will be configurable as part of the overall search configuration: https://cascade.emory.edu/entity/open.act?id=82fbd4580ae7209811020203d5497c70&type=page.

**Comment by nikdragovic** [comment]
Awesome, thank you for the link.
