### ISSUE TITLE
Create new pattern Compound::Search-Result

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#209]

**Comment by kristianserrano** [comment]
@laurenhamel do we actually need this pattern for anything at launch?

**Comment by laurenhamel** [comment]
I'm thinking this is another instance where the pattern may not get implemented at launch. I imagine this will only really get rolled out once we start integrating the redesign patterns into library applications.

**Comment by laurenhamel** [comment]
Closing because this was marked as invalid. A new issue can be opened in the future if circumstances related to this changes.
