### ISSUE TITLE
Create new pattern Compound::Sidebar-List

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#210]

**Comment by laurenhamel** [comment]
@kristianserrano, I'm trying to more evenly distribute story points, and since this looks like low hanging fruit that I'll need it to work on the Staff Bio template, I'm going to reassign myself to this issue.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing whenever you get a chance.

**Comment by laurenhamel** [comment]
This should get deployed with #170.
