### ISSUE TITLE
Create new pattern Compound::Notification

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#211]
## Testing

`pattern-library` [compounds-notification](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=compounds-notification)

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. I anticipated that we'll want to group this into the header pattern (#201), so I left a placeholder within the header, where we'll be able to drop this in when ready.

**Comment by laurenhamel** [comment]
This is ready for acceptance. See above for testing links. Do note, this is only visual and functional testing and acceptance at this time as this pattern has not yet been integrated into our template pages.
