### ISSUE TITLE
Create new pattern for Compound::Feed

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#213]
## Testing

`pattern-library` [compounds-feed](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=compounds-feed)

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance. Do note, this is static content for the time being, but once we start incorporating this into template-level patterns, we will be pulling in live feed data from Trumba, etc.

**Comment by nikdragovic** [comment]
@laurenhamel Accepted, looks great, so much better than existing Trumba feeds.
