### ISSUE TITLE
Generate Template Patterns

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#226]
- [x] Export patterns from the pattern library to the templating engine.
- [x] Ensure that includes are still working inside the templating engine.

**Comment by laurenhamel** [comment]
If we're thinking of this issue as the actual export of the template patterns and their partials into the templating engine, then this is almost a recurring issue with each sprint cycle where we're working on patterns.

**Comment by kristianserrano** [comment]
I'm going to convert this to an Epic and move it toward the bottom of the stack.

**Comment by laurenhamel** [comment]
This is no longer relevant as the templating engine is being decommissioned for Phase 2.
