### ISSUE TITLE
Architect template patterns

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#227]

**Comment by laurenhamel** [comment]
Should this be an epic? And if so, @kristianserrano, do we want to use this as a parent epic to the epics we're considering creating for each template?

**Comment by nikdragovic** [comment]
This can be an epic if needed. Are there lower-level components that need to be epics too (like molecules or organisms)?

**Comment by kristianserrano** [comment]
This and a few others were super high-level issues we had put on the board back in December. Since then, I think we've outgrown them in terms of what we've been tracking on the board. I didn't do anything with them because I want to bring them to our meeting to discuss further.

**Comment by laurenhamel** [comment]
This was completed and moved to Phase 2.
