### ISSUE TITLE
Add Anchors to Headings in pattern Molecule::Block

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#231]
Add anchors onto headings within Block molecule.

## Testing

`pattern-library` [molecules-table-of-contents](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=molecules-table-of-contents)
`pattern-library` [templates-info](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-info)

**Comment by nikdragovic** [comment]
From old/duplicate isssue: 

As a content producer/editor, I want to copy a link to a heading on another producer/editor’s page in staging, so that I can embed a link to that content in the body text of my page.

Acceptance criteria: Instructions on how to complete the above (added as a comment to the ZenHub issue).

Questions:
Is it permissible to use this feature to manually generate a table of contents?
Do I need to indicate what pattern/s (block type) this applies to?
What release and sprint apply?
What repo should I put this in?

**Comment by kristianserrano** [comment]
@nikdragovic I'm assuming this is only going into the block pattern used in info pages and some other pages using that pattern (Periodicals uses it for example). Is that correct, or is this supposed to apply only to Info pages as a feature of that page type?

**Comment by kristianserrano** [comment]
@laurenhamel this is ready for us to review. I do have some concerns with the amount of css generated as a result of the placement of the .anchor style definitions in the `tokens-heading/_skin.scss` file. It's not a shower stopper though.

**Comment by nikdragovic** [comment]
@kristianserrano We may have covered this in our discussion on Tuesday, but the first option you mentioned sounds good. Does this issue include the ToC toggle? I see there are some issues that mention that in template-sass.

**Comment by kristianserrano** [comment]
@kristianserrano Yes, I've already added the toggle in the DD in Cascade. I'm currently working on pushing the changes to `templating-engine` for a PR there as well.

**Comment by kristianserrano** [comment]
@laurenhamel this is ready for testing.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance. At present, this has not yet been integrated into any of the live pages, but you can see a preview on the patterns that I linked to above. @kristianserrano mentioned that we still need to add checkboxes into DDs for the page types where we want to enable this functionality.

**Comment by nikdragovic** [comment]
@laurenhamel Accepted. Thanks for explaining so thoroughly. Let's add an issue for post-launch for that checkbox?

**Comment by laurenhamel** [comment]
@nikdragovic, yes, I think that would make sense, or at the very least, let's make sure we add an issue to capture that work so that we can prioritize it accordingly.
