### ISSUE TITLE
Fix exhibition and gallery templates

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/Pattern-Library#268]
This fixes the exhibition template not displaying hero images, and the gallery template's current listing not having a clickable area while button/link content has not yet been populated.

## Testing

`dev` [/events-and-exhibits/exhibits/punks-not-dead](http://dev.libraries.emory.edu/events-and-exhibits/exhibits/punks-not-dead)
`qa` [/events-and-exhibits/exhibits/punks-not-dead](http://qa.libraries.emory.edu/events-and-exhibits/exhibits/punks-not-dead)

`dev` [/events-and-exhibits/exhibits/](http://dev.libraries.emory.edu/events-and-exhibits/exhibits/)
`qa` [/events-and-exhibits/exhibits/](http://qa.libraries.emory.edu/events-and-exhibits/exhibits/)

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance and has been deployed to `qa`. Check the description above for testing links.

**Comment by nikdragovic** [comment]
@laurenhamel I am seeing the hero in dev but not qa.

**Comment by laurenhamel** [comment]
@nikdragovic, this should also be fixed now. Because the `qa`, `staging`, `production` environments use the CSS stylesheets from `template.library.emory.edu`, I believe it was ultimately trying to look for the image on that domain. I changed the image path for the hero intros to use absolute paths, so all should be working now.

**Comment by nikdragovic** [comment]
@laurenhamel Accepted, thanks!
