### ISSUE TITLE
Ensure header styles match typography in design system

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#272]
Some page types do not match the typography in the design system (https://www.figma.com/file/BQZEgrI0UZk6McDQDqqqYVhu/Emory-System?node-id=0%3A16)

Here is an example:
http://staging.libraries.emory.edu/about/organizational-framework

Priority for stakeholders: High but not urgent

**Comment by kristianserrano** [comment]
@nikdragovic didn't we look this over during a meeting? @laurenhamel do you happen to recall where we left off with this?

**Comment by laurenhamel** [comment]
Yes, we did. Everything should've been corrected, but I recall some mention of removing/replacing the `h1-alt` header styles with just `h1` styles because of font sizing.

**Comment by laurenhamel** [comment]
This was completed and moved to Phase 2.
