### ISSUE TITLE
Fix conditional checks for link customizations across templates

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/Pattern-Library#277]
In reference to [this comment](https://github.com/emory-libraries/web-redesign/issues/170#issuecomment-513225149), conditional checks for link customizations within templates need to be fixed to force a strict type and value comparison. This means that we'll need to convert any handlebars instances of
```handlebars
{{#if (gte (indexOf link-customizations 'Label') 0)}}...{{/if}}
{{#if (gte (indexOf link-customizations 'Label') 0)}}...{{/if}}
```
or similar to be
```handlebars
{{#if (not (eq (indexOf link-customizations 'Label') false))}}...{{/if}}
{{#if (not (eq (indexOf link-customizations 'Label') false))}}...{{/if}}
```

In order for this to work across both the pattern library's and templating engine's handlebars engines, we'll also need to make sure that the `indexOf` helper returns `false` (rather than `-1` like in JS) when an item is not found within a string or array and the `eq` helper uses strict comparisons (`===`).

**Comment by laurenhamel** [comment]
@nikdragovic, I went ahead and added these fixes into `qa`. I can't remember which pages you were specifically having trouble with, but if you have the time, please do test again,and see if this fixed it.

**Comment by nikdragovic** [comment]
@laurenhamel Thanks so much. It appears to be behaving as expected now. I tested on the tools page we looked at earlier:

http://qa.libraries.emory.edu/tools1

And also on the About page that was confusing CTF earlier this week:

http://qa.libraries.emory.edu/about/index
