### ISSUE TITLE
Integrate header, footer, and sidebar into all templates

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/Pattern-Library#282]
### Global Mutations

- [x] Hours
- [x] Search
- [x] Navigation
- [x] Header
  - [x] Select a Library
- [x] Footer
  - [x] Global-Level Data
  - [x] Template-Level Data

#### Generic Templates
- [x] Home Page
- [x] Landing Page
- [x] Cover Page
- [x] Info Page
- [x] Form Page
- [x] Index Page
- [x] Hours Page

#### News Templates
- [x] Periodical Page

#### Exhibitions Templates
- [x] Exhibit Page
- [x] Gallery Page

#### Events Templates
- [x] Event Page
- [ ] Calendar Page

#### Staff Templates
- [x] Staff Directory Page
- [x] Subject Librarian Page
- [x] Bio Page

#### Services Templates
- [x] Service Directory Page

#### Tools Templates
- [x] Tool Page

#### Materials Templates
- [x] Material Page

#### Research Help Templates
- [x] Research Help Directory Page
- [x] Research Help Page

### Sidebar Integrations

- [x] Material Page
- [x] Tool Page

**Comment by kristianserrano** [comment]
@laurenhamel I'm wondering if we should create and HBS file for the header and footer first, and then we can quickly touch each template to put insert the include and remove the current placeholders. Then when that pattern is done, it'll populate later. We could even move the current styles for the placeholders into the CSS for those patterns.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm really impartial as to whether we do it now or later. I think it will just depend on when we get to header/footer stuff since it seems to have landed towards the middle of things in terms of prioritizing issues for this sprint. I feel like we should especially focus on developing any remaining templates that are outstanding first and foremost, then when we get to header/footer stuff, we can likely split the work.

**Comment by kristianserrano** [comment]
@laurenhamel fair enough.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm crossing off the Analytics mutations line since I don't think we actually have any mutations that need to be done there. Instead, I'm going to add a new section for other miscellaneous to-do items. I think the analytics stuff mostly encompasses adding a check for production/preview into our default layout to either include and load the analytics tracking script or not based on environment.

**Comment by libdgg** [comment]
NOTE: #282 is blocked because of its dependencies that are still waiting in queued. This is also reflected in the checklist as there’s one outstanding item still in the to-do list.

**Comment by laurenhamel** [comment]
This was completed as part of Phase 2 work.
