### ISSUE TITLE
Create new pattern Template::Hours

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#283]
Two approaches: non-responsive table vs. card for each location. We're leaning toward a card for each location to be more usable across various screen sizes.

## Testing

`qa` [/hours/](https://qa.libraries.emory.edu/hours/)

**Comment by kristianserrano** [comment]
@nikdragovic, @laurenhamel and I just had a conversation about standardizing the labels for semesters in the Hours template. We'd like to switch it from a text field to a dropdown, but we'll need a list of labels the library uses for different periods/semesters. Can you reach out to Collin or Oliver to get a definitive list for us to put into the DD?

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. One thing to note, I added #314 as an enhancement to correct any table sizing/layout weirdness that may occur after having selected one or more new dates to be displayed.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for testing. See link above.

**Comment by kristianserrano** [comment]
@nikdragovic this is ready for review.

- QA: https://qa.libraries.emory.edu/hours/
- Pattern Library: http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-hours

**Comment by nikdragovic** [comment]
@laurenhamel @kristianserrano Accepted.
