### ISSUE TITLE
Exhibitions gallery not sorting by date

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#286]
The exhibitions gallery appears to be properly sorting current vs past, but the past exhibits section looks like it is presenting in the order entered into Cascade as opposed to sorting.

https://staging.libraries.emory.edu/events-and-exhibits/exhibits1

https://cascade.emory.edu/entity/open.act?id=9a3817740ae720982dc27e3375122ec1&type=page

If there is more than a small amount of development effort, it may be wise to ask them to sort everything manually. We'd need to ask soon, though.

**Comment by laurenhamel** [comment]
Sorting needs to be added on start date.

**Comment by laurenhamel** [comment]
This was related to the templating engine, which is no longer in use for Phase 2. The Gallery page has also been reworked as part of Phase 2, which should fix any such issues.
