### ISSUE TITLE
Selecting return when searching on home page does not work

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/Pattern-Library#319]
I believe most users are expecting to hit enter and see search results as opposed to the search button. I suspect we will get reports of search no working when it is working but the user must select search. I consider this a bug but feel free to relabel if you believe differently.

**Comment by laurenhamel** [comment]
I anticipate that this can be dropped to a 1 point issue as the search box's Vue component input box is merely missing a listener for the enter/return key.

**Comment by laurenhamel** [comment]
This was completed and moved to Phase 2.
