### ISSUE TITLE
Homepage: Update hero button

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#322]
The hero image on the homepage has a button overlay.  That button should be a link, just like the title.

**Comment by kristianserrano** [comment]
@rosy1280 I've got this in place. You can see it in action here:
http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home

**Comment by rosy1280** [comment]
@kristianserrano i suspect that something went wrong with the change that you made earlier today, the footer on prod and staging is acting up.  

right now the [pattern library](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home) displays fine.  and the view [inside cascade](https://cascade.emory.edu/entity/open.act?id=34c05b8b0ae72098230fc98155d59e2d&type=page) also appears fine.  However when I go to [prod](https://prod.libraries.emory.edu/) or [staging](https://staging.libraries.emory.edu/) the footer is all out of whack.  

can you please roll back the change and investigate what went wrong?

**Comment by kristianserrano** [comment]
@rosy1280 The published pages have the footers wrapped in an extra footer element with the same class. If you remove one level of nesting, the footer renders normally. This double footer nesting doesn't exist in Cascade or the Pattern Library. I assume if those pages were republished, the footer would not be nested in another footer.

**Comment by rosy1280** [comment]
@kristianserrano i'm going to leave the ticket in testing until that's resolved, just in case.  but looking at your commit i see no way that could be the issue (unless it was something else in that branch you weren't aware of)

**Comment by rosy1280** [comment]
They fixed the footer issue and I submitted the request to change the badge to a button.
