### ISSUE TITLE
Staff and Subject Librarian pages: Search is not working

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#323]
The search on the following templates is not working as expected:

- [x] [Staff directory](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/60-templates-staff-staff-directory/60-templates-staff-staff-directory.html)
- [x] [Subject librarian directory](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/60-templates-staff-subject-librarian-directory/60-templates-staff-subject-librarian-directory.html)

They should behave similar to the search on [services directory](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/60-templates-services-service-directory/60-templates-services-service-directory.html)

**Comment by kristianserrano** [comment]
I got the Staff Directory working locally. Working on Subject Librarians next.

**Comment by kristianserrano** [comment]
The Subject Librarians Directory is working locally and is ready for deployment.

**Comment by rosy1280** [comment]
@kristianserrano can you deploy this today?

**Comment by kristianserrano** [comment]
@rosy1280 Yes. These are now deployed.

Subject Librarian Directory: http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-subject-librarian-directory

Staff Directory: http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-staff-directory

**Comment by rosy1280** [comment]
@kristianserrano when you search the staff directory and then clear the search, content doesn't reset (i.e. we don't see all the content anymore).  

See the services directory as an example: https://staging.libraries.emory.edu/services/index.html

I'm going to move this back to in progress.  Fixing this is a lower priority than #329

**Comment by kristianserrano** [comment]
@rosy1280 I'm sorry, but I'm not able to duplicate that issue on the live pattern library. Whether I click the `Cancel` button or delete the search query and press `Enter`, the content restores for me. I tried this in both Chrome and Firefox.

I'll follow up with you on Slack, and perhaps we can do a call from there.

**Comment by rosy1280** [comment]
huh.  i can't get it to do that either.  perhaps i just needed to refresh.

**Comment by rosy1280** [comment]
tweaks to search to ensure that clearing the search results returns the page to the pre-search list.

**Comment by rosy1280** [comment]
@kristianserrano i just wanted to make sure that my slack comment to you yesterday didn't confuse anything.  the priority should be getting the page to reset to its pre-search state once you clear the search.  

if by some miracle fixing that issue also fixes some of the wonkiness happening in search (e.g. what you see when you search for rosalyn as an example) then that's great, but there are more pressing issues like the lack of a button on the services page.

**Comment by kristianserrano** [comment]
@rosy1280 Yes, I saw. Thank you for the clarification. This is fixed, deployed, and available for review.
http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-service-directory

**Comment by kristianserrano** [comment]
@rosy1280 the sort order on reset of the Staff Directory should be normal now. Can you please test?

I also have a fix in place for the Subject Librarian Directory subject area links.

There are two things HH will need to do:

1. Change the subject area links to use `+` between words in the subjects area names instead of spaces.
2. Add a `"selected: {subject}"` property to the `defaults` on the `eul-filter-dropdown` Vue component which grabs the subject paramater from the URL.

I'll reach out them about making these changes.

I also have the subject librarian directory page changing the URL in the address bar whenever a new subject is selected from the dropdown, and the query string is removed altogether when the filter is cleared.

**Comment by kristianserrano** [comment]
I've followed up with Fernando. He said he will review and let me know if he needs anything else from me.
