### ISSUE TITLE
Add Aria attributes or labels to form elements

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#328]
The attached [report from CPA](https://app.zenhub.com/files/68927668/4c766af2-2099-4b89-80e7-54b12fdd93af/download) suggests adding either labels or aria attributes to form elements.  On our site these appear specifically in the following locations:

- [x] Dropdowns like the [Select a Location dropdown](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-header)
- [x] The multi-search box which appears when you click the [Search button](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-header) on the right navigation pane and on the [Homepage](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home)
- [x] Filter boxes which includes the ones on the [Services Directory](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-service-directory), the [Staff Directory](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-staff-directory), and the [Subject Librarian Directory](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-subject-librarian-directory)

Consider which of the options they suggest makes the most sense and implement them.

**Comment by rosy1280** [comment]
the attached report suggests adding either labels or aria attributes to form elements.  on our site these appear specifically in the following locations
- [ ] Dropdowns like the [Select a Location dropdown](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-header)
- [ ] The multi-search box which appears when you click the [Search button](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-header) on the right navigation pane and on the [Homepage](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home)
- [ ] Filter boxes which includes the ones on the [Services Directory](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-service-directory), the [Staff Directory](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-staff-directory), and the [Subject Librarian Directory](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-subject-librarian-directory)

**Comment by rosy1280** [comment]
If you choose to use aria labels, you should also make sure that [HTML Landmarks](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html) are properly marked as well.  If you choose not to go with aria labels, this should be broken out into a separate ticket and include in Epic #330

**Comment by kristianserrano** [comment]
@rosy1280 I've updated the documented inputs, searches, and selects with ARIA labels.

[Homepage template](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/60-templates-generic-home/60-templates-generic-home.html)

[Subject Librarian Directory template](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/60-templates-staff-subject-librarian-directory/60-templates-staff-subject-librarian-directory.html)

[Staff Directory template](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-staff-directory)

[Services template](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/60-templates-services-service-directory/60-templates-services-service-directory.html)

**Comment by kristianserrano** [comment]
Changes HH will need to make in velocity to match the pattern library.
- Main header for all pages (.header as a parent of .header-main): Add role="banner" and aria-label="Main navigation and search"
- Main navigation wrapper (.nav-menu-main): Add aria-label="Main navigation" and role="navigation"
- Each submenu in main navigation (.subnav-menu-main): Add aria-label="Submenu navigation" 
- Utility nav menu (.nav-menu-utility): Add aria-label="Utility navigation"
- Main site footer (.footer): Add  aria-label="Main footer"
- Radio inputs in search menu in header and homepage (.search-menu-toggle): Add aria-labels for each search option
- Main search input in header and homepage (input.-search.-[big || small].search-box): Add aria-label="Main search text input"
- Location list select (.branding-header-dropdown-menu): Add aria-label="Select a location"
- For notification dismissal buttons: Add <title> element as first child of <svg> element with "Dismiss notification" as the text node within title.
- Staff Directory page search: Add aria-label="Enter a name, title, library, phone number, or email to filter the list of staff"
- Services page search: Add aria-label="Enter keywords to search for a service"
- Subject Librarian Directory page search: Add aria-label="Select a subject area to filter the list of subject librarians"
