### ISSUE TITLE
Consider adding page language attribute

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#333]
Every page seems to be missing this attribute. From [the W3C website](https://www.w3.org/International/questions/qa-html-language-declarations):
>Always use a language attribute on the `<html>` element. This is inherited by all other elements, and so will set a default language for the text in the document head element. Note that you should use the `<html>` element rather than the `<body>` element, since the body element doesn't cover the text inside the document's head element.

>If you have any content on the page that is in a different language from that declared in the html element, use language attributes on elements surrounding that content. This allows you to style or process it differently.

**Comment by kristianserrano** [comment]
@rosy1280 I've added this to the "Contents Page" template in the "Template Assets" site in Cascade.
I published the index page on staging with the attribute in place.
https://staging.libraries.emory.edu/
