### ISSUE TITLE
Update pattern library hours page so there is one dropdown per semester

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#338]
In ticket #329 we added extra hours and locations and a bug appeared in pattern library where a fall and spring semester appeared for each library that has hours.  update the pattern library to fix this bug.

- [x] one dropdown per semester
- [x] choosing the dropdown for a semester should allow you to filter on each of the libraries.

**Comment by kristianserrano** [comment]
@rosy1280 There is now one dropdown per semester and the dropdown for the semester changes hours for each of the libraries. These were confirmed and resolved with the work performed on [#264](https://app.zenhub.com/workspaces/website-redesign-5be9f5af4b5806bc2bf3ddda/issues/emory-libraries/web-redesign/264).
