### ISSUE TITLE
Add button to the Services Directory Page

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#339]
Currently the services directory lacks a way of linking to the page that it references.  See the pattern library screenshot below:

![Screen Shot 2019-12-05 at 2.09.43 PM.png](https://images.zenhubusercontent.com/5c35178086008d0a2e1830d9/6c6fc71c-173f-4692-a9ae-ef1f63c8495b)

The original designs by Viget show that there should be a button below the description.  See the Figma screenshot below:

![Screen Shot 2019-12-05 at 2.17.30 PM.png](https://images.zenhubusercontent.com/5c35178086008d0a2e1830d9/a5dcec6e-bcb5-4388-8de7-6282e2de657e)

Update the Pattern Library according to the following acceptance criteria:

- [ ] Include the [Button Form](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=atoms-button-form) atom
- [ ] The button form item should appear below the description text.
- [ ] When the collapsed area unfurls, the button should also appear, it should not appear before then.

**Comment by kristianserrano** [comment]
The button is fixed, deployed, and available for review.
http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-service-directory

**Comment by rosy1280** [comment]
qa issue submitted to hannon hill for inclusion in the cascade site.
