### ISSUE TITLE
Review alerts branch and give feedback

### ISSUE THREAD

**Issue by jonmbodnar** [emory-libraries/Pattern-Library#34]
Kristian, 

Review the alert mustache, markdown, and scss files for the alerts in the alerts branch:

  * source/_patterns/molecules/50-alerts/*
  * source/css/scss/pattern-specific/_alerts.scss

Then talk with me about the following three questions:

  1. Are you cool with my setting them as molecules? 
  2. Are you cool with their styles being pattern specific?
  3. Do you want any changes to the text I provided for them?

**Comment by kristianserrano** [comment]
A few things I'll adjust:

- Refactor Sass using Bootstrap 2 styles and nesting
- Merge patterns into one mustache file
- Pull atoms-paragraph pattern into alert
- Add heading to pattern

**Comment by kristianserrano** [comment]
@jmbodnar I've made changes and submitted a pull request for review in #35 as noted above.

**Comment by jonmbodnar** [comment]
Thanks.
