### ISSUE TITLE
Include library location in staff search function

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#380]
Currently the staff directory does a fuzzy match on `'name', 'title', and 'email'`.  [PR#374](https://github.com/emory-libraries/Pattern-Library/pull/374/) removed `library` from the fuzzy match.  

To improve the current "search" functionality, lets do the following:

- [ ] add `library` back to the fields searched
- [ ] tighten up the [fuzzy match threshold](https://github.com/emory-libraries/Pattern-Library/blob/c250214b054228e8f89437eac7b94159913b76d4/src/js/index.js#L752)

This should satisfy the issue reported in [INC03355670](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D53b094911b774450a8441f4ead4bcba7%26sysparm_record_target%3Dtask%26sysparm_record_row%3D4%26sysparm_record_rows%3D4%26sysparm_record_list%3Dactive%253Dtrue%255Eassigned_to%253Djavascript%253AgetMyAssignments%2528%2529%255EORDERBYDESCstate).  I'll let the user know we have gone this route rather than redesigning the entire page and adding the drop down requested.

**Comment by CB987** [comment]
Have added library back into the searched fields. 
Currently working on the degree of fuzziness of the search.

**Comment by rosy1280** [comment]
finally deployed to production
