### ISSUE TITLE
Need styles for table options presented in Cascade template

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#4]
@jonmbodnar mentioned that he'd be willing to take on adding styles for our tables to match the Cascade template. I can help with that, Jon. There are some elements we should account for that might not be present in the existing styles such as table caption and table footer.

**Comment by jonmbodnar** [comment]
Started work on the tables

**Comment by kristianserrano** [comment]
Found a way to do conditional html attributes.
# HTML Template
`<table {{# hasClass}}class="{{ styleModifier }}"{{/hasClass}}>`
# Mustache
`{{> molecules-table-template: tile(hasClass: true) }}`
or
`{{> molecules-table-template(hasClass: false) }}`
