### ISSUE TITLE
Fix selector for site footer container styles

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#41]
Selector for footer in [source/css/scss/base/_layout.scss](https://github.com/emory-libraries/Pattern-Library/blob/master/source/css/scss/base/_layout.scss) refers to `body > footer` which breaks on 'View All' in Pattern Lab. Should instead refer to #site-footer for more specificity.

**Comment by laurenhamel** [comment]
Should we consider closing this issue since we've now moved to the Node version?

**Comment by kristianserrano** [comment]
Looking at the pattern for the footer, it looks like the selector `footer {...}` would be too broad as we could technically have multiple footers within a single page. I'm inclined to use an id of `#site-footer {...}` as the selector to identify and target the main site-wide footer instead. Thoughts?
