### ISSUE TITLE
Meta section of content

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#54]
I'm thinking we should create a meta section in the navigation that could contain information about the pattern library itself, including the introduction and pattern states. It'd appear at the top of the All listing, but not on every pattern pages, which would then focus the individual pattern pages on the pattern themselves.

Thoughts?

**Comment by laurenhamel** [comment]
Agree with this change. I think you handled this with the `pattern-tweaks` branch.
