### ISSUE TITLE
Create pattern for Atom::Map

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/Pattern-Library#97]

**Comment by laurenhamel** [comment]
I decided to go with a dynamic map approach instead of using static images, but I had to do some digging to figure out to a more cost-effective approach in doing so than relying on the Google APIs due to pricing changes (more information to follow). Thus, I decided to build this pattern using a two-fold approach: (1) By default, I'm rendering a custom map generated by [Leaflet](https://leafletjs.com/) that sources its map data and images from [OpenStreetMap](https://www.openstreetmap.org/), and (2) I'm also generating an embedded Google map (using the same embed URL syntax like the one found by clicking the *Share* link on their public-facing site) as a `<noscript>` fallback.

Here is some of my reasoning for taking this approach:

1. Without actually using one of Google's APIs, the embedded Google maps have limited flexibility (for instance, there's no way to hide the white place card box and just show the pinned location on the map). These embedded maps are also using URLs that are intended for sharing via Google's public-facing, undocumented consumer API, so there's no guarantee that these links will continue to work indefinitely.

2. OpenStreetMap data, and its various providers, appears to be a promising solution that could potentially lead to some future enhancements for our site and the library as a whole. It's a leading, open-source alternative to paid map service providers, such as the Google Maps API, and depending on how you retrieve and use the data, it can offer added flexibility that doesn't inherently come with other paid service plans. 

Recent changes to the pricing model for the Google Maps API meant that we would likely incur a good deal of fees if we opted to use one of their many APIs. That is, they did away with their free tiers for the Embed API, Static API, and even their JavaScript API. However, I did manage to find a slight workaround using their Places API: While usage of the Places API is will still incur some volume fees in the future if we need it, all requests to retrieve *Basic* place data from the API is actually free (so overall API usage fee based on volume but no per-query fees). You can refer to their new [Pricing Sheet](https://cloud.google.com/maps-platform/pricing/sheet/) for more details.

Luckily, after some poking around, I found out that Google grants you a free 1-year trial to use any of their APIs plus a $300 credit towards their services when you sign-up with a new account, so I was able to go ahead and pull out some preliminary place data for each of the Emory libraries, which I've now incorporated into our Pattern Library. I'm thinking that this might just be all the data that we'll need, unless we decide to add additional places in the future. I'm mainly using this data to extract information such as geographic coordinates, which can then be used in term to render our maps.

In terms of potential future enhancements, here's what I'm thinking could happen:

- If we decided we wanted to use a Google API full-time to render maps on the fly, such as their Embed API or Static API, we could easily take that route and simply update this pattern to use their  API. This would allow for more flexibility in rendering maps as well as a more streamlined approach.

- The other approach we could take towards future enhancements, as an alternative to using one of the Google APIs, would be building out and hosting our own [map tile server](https://wiki.openstreetmap.org/wiki/Tile_servers), which we could then target for any map imagery. If we opted to do so, I see the potential benefits being 3-fold:
1. We wouldn't have to rely on another provider's server (this pattern is currently configured to use the Wikimedia server) to render our map imagery. This would mean better performance and exclusivity when using maps across any of our sites and apps. 
2. This could potentially be a new resource added to the library that faculty, staff, and students could use. Of course, having control over the server would allow us to decide who could access it and for what reasons.
3. We would have the flexibility to potential build new [tile layers](https://wiki.openstreetmap.org/wiki/Featured_tile_layers), which could offer additional geographic information to our end users. For instance, we could decide to build a layer that features bus routes, walking trails, or even an illustrated campus map.

**Comment by kristianserrano** [comment]
Hmmm... I'm starting to wonder if we're looking to over engineer this. Google Maps in its previous model would have been an easy solution, but Google pulled a Google.

Something I just found (and maybe Nik or somebody mentioned this in the past)...
http://emap.fmd.emory.edu/website/campus/index.htm#?queryzoom=Yes&Query=(bldg='1980')

This is a thing that Emory has. We could easily create images from screen captures and link out to it. The cards seem to have additional information including parking and directions.

**Comment by laurenhamel** [comment]
I'm digging some into the link you shared, but right off the bat, I'm not seeing anything that would allow us to embed that specific map let alone with a place/location highlighted. It's pulling from Google and using their JavaScript API, so it's subject to the same "Google being Google" problem.  I did notice that they do use some overlays on top of the Google Map, though, which could potentially be pulled into the Leaflet plugin if we wanted to try that but, like you mentioned, that could all be over-engineering and/or work that should be put off as a potential enhancement.

**Comment by kristianserrano** [comment]
Yeah, there's no API for it, and I have no idea how they'll be affected by the change in pricing as well.

Ultimately, we just need a map image to put in place. Enhancement could come later. I think we should put it up in the backlog and prioritize from there.

And thank you for looking into all of this in such depth. I appreciate you taking the time to explore the options.

**Comment by laurenhamel** [comment]
I went ahead and added a variation of this pattern to allow for images/screenshots instead of an actual map object where needed. This should hopefully cover all the bases for the time being.
